# Common Homebrew dependencies for macOS machines.

brew "lsd"
brew "bat"
brew "fzf"
brew "fd"
brew "ripgrep"
brew "git-delta"
brew "gh"
brew "btop"
brew "dust"
brew "duf"
brew "fastfetch"
brew "neovim"
brew "zellij"
brew "zoxide"
brew "lazygit"
brew "navi"
brew "starship"
brew "mise"
brew "gemini-cli"

cask "ghostty"
cask "cmux"
cask "hammerspoon"
cask "raycast"
cask "font-jetbrains-mono-nerd-font"
cask "font-d2coding"
