[tools]
bun = "latest"
node = "24"
python = "3.13"
uv = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:aristocratos/btop" = "latest"
"aqua:bootandy/dust" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:cli/cli" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:denisidoro/navi" = "latest"
"aqua:fastfetch-cli/fastfetch" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:lsd-rs/lsd" = "latest"
"aqua:muesli/duf" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:starship/starship" = "latest"
"aqua:zellij-org/zellij" = "latest"

[settings.node]
corepack = true
